### PR TITLE
`scale!!(y, x, a)` considers scalartype of `y` for determining result type 

### LINKED ISSUE #10: Bangbang methods fail for mixed scalar types
Noticed the following behaviour:

```julia-repl
julia> a = [1, 1]
2-element Vector{Int64}:
 1
 1

julia> b = Complex{Int}[1, 1]
2-element Vector{Complex{Int64}}:
 1 + 0im
 1 + 0im

julia> scale!!(b, a, -1)
2-element Vector{Int64}:
 -1
 -1

julia> b
2-element Vector{Complex{Int64}}:
 1 + 0im
 1 + 0im
```

At first glance, it seems like when the scalartype of `a` is not a subtype of the scalartype of `b`, we dispatch to broadcasting:
``scale!!.(y, x, α)``, which for numbers doesn't work in-place. I think it's fixed with ``y .= scale!!.(y, x, α)``, so I'll add some tests and open a PR.

### PR DESCRIPTION
**Pull request by lkdvos**
This fixes #10 .

### CODE REVIEW

File: src/number.jl [hunk 1]
```diff
@@ -14,8 +14,12 @@ scalartype(::Type{T}) where {T<:Number} = T
 #-----------------
 # note: required to make scale(NaN, 0) = 0
 @inline scale(x::Number, α::Number) = (iszero(α) ? zero(x) : x) * α
+@inline function scale(y::Number, x::Number, α::Number)
```
Comment (Jutho) [inline src/number.jl:17]: I don't think this 3-arg `scale` method makes sense, so I would just take this as the definition for `scale!!`

Comment (lkdvos) [reply src/number.jl:17]: I agree, but it's a bit annoying because the natural definition for `promote_scale(y, x, a)` uses this. I can also turn it around, and make `scale!!(y::Number, x::Number, a::Number)` call `promote_scale(y, x, a)` and define the type promotion in that function. which might be better?

Comment (Jutho) [reply src/number.jl:17]: Ok yes, I see. I guess having this 3-arg `scale` is not too bad after all. Then at least everything is nicely homogeneous in how it is implemented.

**Review by Jutho — APPROVED** [review]
